apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  USER_NAME: c2VjcmV0VXNlcg==  # Texto codificado en base64 (por ejemplo: "secretUser")
  PASSWORD: c2VjcmV0UGFzc3dvcmQ=  # Texto codificado en base64 (por ejemplo: "secretPassword")